version: '3'

services:
    mysql:
        image: mysql
        container_name: sf4bo_container_mysql
        restart: always
        ports:
            - "3307:3306"
        volumes:
            - ./docker/data/db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: sf4bo
            MYSQL_USER: sf4boadmin
            MYSQL_PASSWORD: sf4bo1dvw8gs
    php:
        build: ./docker/php-fpm
        ports:
            - '9000:9000'
        container_name: sf4bo_container_php
        volumes:
            - ".:/var/www/sf4bo:cached"
            - "./docker/logs/sf4bo:/var/www/sf4bo/var/logs:cached"
        links:
            - mysql
    nginx:
        build: ./docker/nginx
        ports:
            - '80:80'
        links:
            - php
        container_name: sf4bo_container_nginx
        volumes:
            - "./docker/logs/nginx/:/var/log/nginx:cached"
            - ".:/var/www/sf4bo:cached"